# Generated by Django 4.2.7 on 2023-12-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='Nombre_De_Ex',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tarjeta_o_cedula',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
